### ISSUE TITLE
[BUG]  error: package com.buf.validate does not exist

### ISSUE THREAD

**Issue by gigi** [bufbuild/protovalidate-java#150]
## Description
Hi. Trying to add compiled dependencies to my java project and got dependencies' issues

## Steps to Reproduce

build.gradle.kts:
```
...
dependencies {
    implementation(libs.liquibase.core)
    implementation(libs.spring.modulith.starter.core)
    implementation(libs.grpc.server.spring.boot.starter)
    implementation("io.grpc:grpc-core:1.64.0")
    implementation("io.grpc:grpc-stub:1.64.0")
    implementation("io.grpc:grpc-protobuf:1.64.0")
    implementation("com.google.protobuf:protobuf-java:4.27.1")
    implementation("build.buf:protovalidate:0.2.1")
}
...
```
buf.gen.yaml:
```yaml
version: v2
managed:
  enabled: true
plugins:
  - remote: buf.build/grpc/java:v1.64.0
    out: build/src/java
    opt: '@generated=omit'
  - remote: buf.build/protocolbuffers/java
    out: build/src/java
```
buf.yaml:
```yaml
version: v2
modules:
  - path: proto
lint:
  disallow_comment_ignores: true
  use:
    - DEFAULT
    - COMMENT_ENUM
    - COMMENT_ENUM_VALUE
    - COMMENT_FIELD
    - COMMENT_MESSAGE
    - COMMENT_ONEOF
    - COMMENT_RPC
    - COMMENT_SERVICE
deps:
  - buf.build/bufbuild/protovalidate
  - buf.build/googleapis/googleapis

```

```bash
 ./gradlew clean build

> Task :compileJava
.../MyServiceProto.java:161: error: package com.buf.validate does not exist
          com.buf.validate.ValidateProto.getDescriptor(),
```

## Expected Behavior

I'd like to generate java classes using `buf generate` command, add dependencies and it shoud work

## Actual Behavior

Broken dependencies

## Environment

- **Operating System**: MacOS
- **Version**: 14.5 (23F79)
- **Compiler/Toolchain**: 21
- **Protobuf Compiler & Version**: 4.27.1
- **Protoc-gen-validate Version**: 
- **Protovalidate Version**: 0.2.1

## Additional Context
Maybe I missed something?

Thanks

**Comment by pkwarren** [comment]
First off, you'll likely need to stay on 3.x version of protobuf-java (remote plugin 25.x). See https://github.com/bufbuild/protovalidate-java/pull/116#issuecomment-2004473247 and https://github.com/grpc/grpc-java/issues/11015#issuecomment-2000234497 - neither the CEL interpreter or grpc-java have updated to the latest 4.x version of protobuf-java due to breaking changes.

To do so, update your `buf.gen.yaml` to specify `remote: buf.build/protocolbuffers/java:25.3` instead of `remote: buf.build/protocolbuffers/java`.

Additionally, the protovalidate module specifies `java_package` so shouldn't be used with managed mode. The generated code is shipped with the `build.buf:protovalidate` artifact in the `build.buf.validate` package: https://github.com/bufbuild/protovalidate-java/tree/main/src/main/java/build/buf/validate. To disable managed mode, try adding this configuration under `managed` in your `buf.gen.yaml` file:

```
managed:
  disable:
    - module: buf.build/bufbuild/protovalidate
```

That should ensure that you can import the generated code from this artifact properly.

**Comment by gigi** [comment]
@pkwarren 
Thanks a lot. This approach works now

```yaml
version: v2
managed:
  enabled: true
  disable:
    - module: buf.build/bufbuild/protovalidate
plugins:
  - remote: buf.build/grpc/java:v1.64.0
    out: build/src/java
    opt: '@generated=omit'
  - remote: buf.build/protocolbuffers/java:v25.3
    out: build/src/java
```

I think it should be added to documentation later :)
